name: Build artifacts

on: push

jobs:
  jar:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # No shallow clones for SonarQube
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew build sonarqube -Dquarkus.package.type=uber-jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Copy resources
        run: cp build/*runner.jar smart-home-server.jar
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: smart-home-server-jar
          path: |
            smart-home-server.jar
            Dockerfile

  docker:
    runs-on: ubuntu-latest
    name: Docker
    needs: jar
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: smart-home-server-jar
      - name: Display files
        run: find .
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: stefanoltmann/smart-home-server-jar:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
