name: Build artifacts

on: push

jobs:
  jar:
    name: JAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build -Dquarkus.package.type=uber-jar
      - name: Copy resources
        run: cp build/*runner.jar smart-home-server.jar
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: smart-home-server-jar
          path: |
            smart-home-server.jar
            Dockerfile-jar

  linux:
    runs-on: ubuntu-latest
    name: Linux binary
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.0.0.2
          native-image: true
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build -Dquarkus.package.type=native
      - name: Copy resources
        run: cp build/*runner smart-home-server && cp src/main/resources/keystore.jks keystore.jks
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: smart-home-server-linux
          path: |
            smart-home-server
            Dockerfile
            keystore.jks

  windows:
    name: Windows binary
    runs-on: windows-latest
    if: false
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.5.0
      - uses: microsoft/setup-msbuild@v1
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.0.0.2
          native-image: true
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew buildNative
      - name: Copy resources
        run: cp build/*runner.exe smart-home-server.exe && cp src/main/resources/keystore.jks keystore.jks
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: smart-home-server-windows
          path: |
            smart-home-server.exe
            keystore.jks

  macos:
    runs-on: macos-latest
    name: macOS binary
    if: false
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.0.0.2
          native-image: true
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build -Dquarkus.package.type=native
      - name: Copy resources
        run: cp build/*runner smart-home-server && cp src/main/resources/keystore.jks keystore.jks
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: smart-home-server-macos
          path: |
            smart-home-server
            keystore.jks

  docker:
    runs-on: ubuntu-latest
    name: Docker Container
    needs: linux
    if: github.event_name == 'push' && contains(github.ref, '/tags/v')
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: smart-home-server-linux
      - name: Display files
        run: find .
      - name: Make binary executable
        run: chmod +x smart-home-server
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: stefanoltmann/smart-home-server:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  docker_jar:
    runs-on: ubuntu-latest
    name: Docker Container (JAR)
    needs: jar
    if: github.event_name == 'push' && contains(github.ref, '/tags/v')
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: smart-home-server-jar
      - name: Display files
        run: find .
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-jar
          push: true
          tags: stefanoltmann/smart-home-server-jar:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
